# Generated by Django 5.0.3 on 2024-04-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storebase',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
