# Generated by Django 5.0.3 on 2024-04-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databas', '0003_remove_storebase_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storebase',
            name='stadium_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
